---
- name: Install Docker Engine locally
  hosts: localhost
  connection: local
  become: yes
  become_user: root
  become_method: enable
  
  vars:
    docker_pkg_dependencies:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

  tasks:
    - name: Ensure /etc/apt/keyrings exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Docker GPG key
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
          | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Docker GPG key file permission
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'
    - name: Add Docker APT repository via tee
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
          | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list
        executable: /bin/bash

    - name: Update apt cache
      apt:
        update_cache: yes    
    - name: Install pre packages
      apt:
        name: "{{ docker_pkg_dependencies }}"
        state: present
        update_cache: no


    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
        update_cache: no

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
